### ISSUE TITLE
required but unused environment variables

### ISSUE THREAD

**Issue by kc9jud** [nd-nuclear-theory/spncci#1]
Trying to import `spncci`:

```
>>> import spncci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/homes/p/pfasano/Research/code/spncci/script/spncci.py", line 106, in <module>
    import su3rme
  File "/global/homes/p/pfasano/Research/code/spncci/script/su3rme.py", line 101, in <module>
    su3rme_data_directory=os.environ["SU3SHELL_DATA"]
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SU3SHELL_DATA'
```

Is this variable needed if not running LSU3shell? @mark-caprio @aemccoy

**Comment by kc9jud** [comment]
Tagging @aemccoy

**Comment by aemccoy** [comment]
The variable is a dummy variable only needed for LSU3Shell.  Global variable dependence on SU3SHELL_DATA has been removed in su3rme.py

**Comment by kc9jud** [comment]
I'm also seeing a dependency on `SPNCCI_SEED_DIR`:

```
>>> import spncci
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/global/homes/p/pfasano/Research/code/spncci/script/spncci.py", line 122, in <module>
    seed_directory_list = os.environ["SPNCCI_SEED_DIR"]
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'SPNCCI_SEED_DIR'
```
